#!/usr/bin/python
# SPDX-License-Identifier: Apache-2.0
import os
import socket
import struct
import sys
import uuid

import config

client_file = '/tmp/sysprobe-{}.sock'.format(uuid.uuid4())
server_file = config.CONFIG_CTL_SOCKET_PATH

retprobe = int(sys.argv[1])
pid = int(sys.argv[2])
func_offset = int(sys.argv[3])
binary_path = sys.argv[4]

unix_domain_socket = socket.socket(socket.AF_UNIX, socket.SOCK_DGRAM)

unix_domain_socket.bind(client_file)
unix_domain_socket.connect(server_file)

bytes_to_send = struct.pack("=IiiQ4096si", 9, retprobe, pid, func_offset, str.encode(binary_path), 0)
unix_domain_socket.send(bytes_to_send)
bytes_to_unpack = unix_domain_socket.recv(len(bytes_to_send))

_, _, _, _, _, ret = struct.unpack("=IiiQ4096si", bytes_to_unpack)

print(ret)

os.unlink(client_file)
