#!/usr/bin/python
# SPDX-License-Identifier: Apache-2.0
import os
import socket
import struct
import sys
import uuid

import config

client_file = '/tmp/sysprobe-{}.sock'.format(uuid.uuid4())
server_file = config.CONFIG_CTL_SOCKET_PATH

event_tgid = int(sys.argv[1])
event_enabled = int(sys.argv[2])

unix_domain_socket = socket.socket(socket.AF_UNIX, socket.SOCK_DGRAM)

unix_domain_socket.bind(client_file)
unix_domain_socket.connect(server_file)

bytes_to_send = struct.pack("@Iiii", 1, event_tgid, event_enabled, 0)
unix_domain_socket.send(bytes_to_send)
bytes_to_unpack = unix_domain_socket.recv(len(bytes_to_send))

_, _, _, ret = struct.unpack("@Iiii", bytes_to_unpack)

print(ret)

os.unlink(client_file)
